apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: dev-

labels:
  - includeSelectors: true
    pairs:
      environment: dev

patches:
  # Патч для сервиса: меняем порт и добавляем externalIPs
  - patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 54321
      - op: replace
        path: /spec/ports/0/name
        value: http
      - op: add
        path: /spec/externalIPs
        value: ["10.0.2.15"]
    target:
      kind: Service
      name: flask-service
      
  # Патч для deployment: реплики + переменные окружения
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: flask-app
